services:
  api-playground:
    build: .
    ports:
      - "8008:80"
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          initial_sync: true
        - action: rebuild
          path: uv.lock
